name: Publish to GHCR
on:
  push:
    branches:
      - master
    paths:
      - 'auth-api/**'
      - 'frontend/**'
      - 'log-message-processor/**'
      - 'todos-api/**'
      - 'users-api/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: microservicesEnv
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    strategy:
      matrix:
        include:
          - service: auth-api
            type: backend
            context: ./auth-api
          - service: frontend
            type: frontend
            context: ./frontend
          - service: log-processor
            type: backend
            context: ./log-message-processor
          - service: todos-api
            type: backend
            context: ./todos-api
          - service: users-api
            type: backend
            context: ./users-api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version file
        id: version
        run: |
            VERSION=$(cat ${{ matrix.context }}/VERSION 2>/dev/null || echo "latest")
            echo "version=$VERSION" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}
          tags: |
            type=raw,value=${{ env.version }}-${{ matrix.type }}           
            type=sha
          labels: |
            org.opencontainers.image.title=${{ matrix.service }}
            org.opencontainers.image.description=${{ matrix.type }} service for microservices architecture
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            com.docker.image.environment.tier=${{ matrix.type }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}